### ISSUE TITLE
Can you give an example on this case?

### ISSUE THREAD

**Issue by gaokeji52** [ometecuhtli2001/mssqlDBcopy#1]
Hi author,

I just need to copy the database from one to another, but I have no idea how to use your project, can you give me some advice?

**Comment by ometecuhtli2001** [comment]
Sure @gaokeji52 !  If you're copying on the same instance, use something like this:  
mssqlDBcopy.exe dsql03:aqc dsql03:copy_of_aqc

If you want the gory details, add /debug at the end.  You can either compile and use from the command line, or in Visual Studio go to the Project menu, Project properties. In the Debug section, add your command line arguments then run the project.

**Comment by gaokeji52** [comment]
Hi Steve, 
Sorry I am a newbie in GitHub, do I need to compile it in Microsoft Visual Studio to get the mssqlDBcopy.exe?

Regards

**Comment by ometecuhtli2001** [comment]
Yes, you will need to compile this in Visual Studio, or another .Net compiler that works with this kind of project.  If you're on Linux, you may be able to use xbuild (part of Mono Project) but note I have not tested this in Linux.  For Windows, if you don't already have Visual Studio, the community edition should work:  https://visualstudio.microsoft.com/vs/community/

**Comment by gaokeji52** [comment]
Hi Steve,

I compile the project in MS VS2017, then I tried to use cmd/git to run the script, while I got this error, which makes me confused, cause I can connect via SSMS tool.

![image](https://user-images.githubusercontent.com/4112282/47470828-ecbd7000-d863-11e8-9842-2339897ea081.png)

![image](https://user-images.githubusercontent.com/4112282/47470857-22faef80-d864-11e8-87d0-b039c98535d2.png)

**Comment by ometecuhtli2001** [comment]
Is there a reason why you're using MINGW?  If you're running on Windows it would be much simpler to use CMD.  I've not used MINGW before so I'm not at all familiar with how it works - it could be there's something that needs to be configured so processes launched under MINGW can access services running in Windows.

**Comment by gaokeji52** [comment]
Hi Matt,

Thanks for your advice, it worked for me when I tried to use CMD, I have just one more question. I need to copy the SRC instance to DST instance via Public Network, what else do I need to do?

I tested in the local network, from IP: 192.168.1.219 to IP: 192.168.1.52, I can't resolve this error:

![image](https://user-images.githubusercontent.com/4112282/47539177-87cd4d00-d92b-11e8-9495-85dca94dd67d.png)

**Comment by gaokeji52** [comment]
the command I type in was mssqlDBcopy.exe .\IDEALSQL:IPSTransaction 192.168.1.52\IDEALSQL:TESTSQL /PATH=C:\test /DESC_CREDS=sa:ips123 /SRC_CREDS=sa:ips123 /debug

**Comment by gaokeji52** [comment]
Thanks Matt, it works!

**Comment by gaokeji52** [comment]
I resolved this out by using xpcmdshell in my MSsql database with 

EXEC sp_configure 'show advanced options', 1;
GO
RECONFIGURE;
GO

EXEC sp_configure 'xp_cmdshell',1
GO
RECONFIGURE
GO

**Comment by ometecuhtli2001** [comment]
The reason why you got the error about trying to access Z: on the destination SQL Server instance is probably because SQL Server doesn't have the right security context to see the drive (I'm guessing it's a drive mapped to a network share). Running NET USE at an elevated command prompt will show you your drive mappings so you can confirm Z: is mapped, then in SSMS run a backup of a (small) database and tell it to send the .bak file to Z:\ and see if it works.  If it doesn't, it's probably a permissions issue - if it does, PM me the full command line you're using and all the debug output and I'll see if it's a code issue.

Also note in the screen capture, you have the password for the sa account on the destination server visible to the Internet - it's a good idea to review screen captures and censor such things. :) Enabling xp_cmdshell is also a security risk - there's usually at least one workaround so you don't have to use it.

**Comment by gaokeji52** [comment]
Hi Steve,
I can solve the problem above, I just wondering is it possible to set the PATH to an FTP path?

**Comment by ometecuhtli2001** [comment]
No, because SQL Server doesn't support directly backing up to FTP, this utility won't either.

**Comment by gaokeji52** [comment]
Oh, that's a bad news, is there other solution that I can back up the SQL via public network apart from using VPN?

**Comment by gaokeji52** [comment]
I make it through Webdav, it's all good.
