### ISSUE TITLE
Can't restore backup when using JDBC connections 

### ISSUE THREAD

**Issue by gaokeji52** [ometecuhtli2001/mssqlDBcopy#2]
Hi Steve,

Your application is good to use, but when trying to backup to a database that has an JDBC connection, it always show up the error message "Exclusive access could not be obtained because the databa is in use",

I just wondering that if possible to use a lock which makes the restoration progress runs in a higher priority? As the JDBC connection is a ready only app.

Regards,
Tecco

**Comment by ometecuhtli2001** [comment]
Hi Tecco,

If I understand right, you're trying to use the copy utility to overwrite a database that has an application connected to it using JDBC and you're running into a problem because the application keeps the destination database in use?  If that's the case, the /REPLACE parameter probably won't help - it was meant to remove an existing database, but it won't do anything about locks or sessions connected to it.  I'm working on another option, /REALLYREPLACE, which will find all sessions using the destination database and kill them. I have some concerns about including this though because it's pretty harsh! In the meantime, you can either kill the session(s) manually, forcibly clear the locks, or shut the application down so it releases those locks.  The last option is the safest as far as database integrity goes.

**Comment by gaokeji52** [comment]
Hi Steve,

Yes, you're thinking that right, I am using the Open source BI solution, the Metabase, to setup the chart, pie, map model to display the data, which links to Mssql server, using JDBC connection, I setup a bat file to synchronize every 30 mins, once I kill that java application, it works, but that's not the solution, right? Is it possible to add the Exclusive Locks to the application and make other applications to access the database with read-only mode?

**Comment by ometecuhtli2001** [comment]
In read-only mode, locks are not relevant because all you can is read.  From what I've read, when running a restore, the RESTORE command is supposed to wait for open transactions to complete then it kicks everyone out of the database.  I haven't found anything about a database-level lock (the nearest equivalent is putting the database into single-user mode).  Your best best is to turn off the Java application during the update, or to force close all of its connections using KILL.  I'll be adding this functionality some time this week or next week along with a lot of warnings in the documentation. :)

**Comment by ometecuhtli2001** [comment]
Sorry for the delay!  I've included a kill switch feature (and some other things) in this newest edition.  There are a few minor changes to the documentation I still need to make, but otherwise try this out and see how it works.
